name: Check, Build, and Run
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Run code checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.2.0
      - name: Setup node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 12.x
      - name: Setup auth for private packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_ORG_ADMIN_TOKEN }}" > ~/.npmrc
      - name: Install deps
        run: npm ci
      - name: Check formatting
        run: npm run format-check
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
  build:
    name: Build action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.2.0
      - name: Setup node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 12.x
      - name: Setup auth for private packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_ORG_ADMIN_TOKEN }}" > ~/.npmrc
      - name: Install deps
        run: npm ci
      - name: Build action
        run: npm run build
      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.12
      - name: Exit with error if there are changes
        if: steps.changes.outputs.changed == 1
        run: exit 1
